spring:
  datasource:
    name: online_shopping
    url: jdbc:mysql://localhost:3306/online_shopping?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      # 每次运行该程序，没有表格会新建表格，表内有数据会清空 ddl-auto: create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    database: 0
    host: localhost
    port: 6379


api:
  service:
    account:
      login: /account/login
      register: /account/register
      logout: /account/logout

jwt:
  header: jwtHeader
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3JlYXRlZCI6MTU0MDYxMzI4N
  expiration: 120000   #毫秒
#  thymeleaf:
#    cache: false